name: Shell Commands

on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
     - name: echo a string
       run: echo "Hello World"
     - name: multiline script
       run: | 
          node -v
          npm -v

  run-second-job:        
    runs-on: ubuntu-latest
    needs: ["run-shell-command"]
    steps:
     - name: python command
       run: |
          import platform
          print(platform.processor())
       shell: python